# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Clem Freeman
tagline:
description:      'Aspiring software developer currently learning at <a href="http://www.epicodus.com/">Epicodus</a> in Portland, Oregon'
url:              http://clem.ninja
shorturl:         clem.ninja

author:
  name:           'Clem Freeman'
  url:            https://twitter.com/clem_free

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
